name: on_audio_query
description: Flutter Plugin used to query audios/songs infos [title, artist, album, etc..] from device storage.
version: 2.6.0
homepage: https://github.com/LucJosin/on_audio_query/tree/main/on_audio_query
# pub.dev: https://pub.dev/packages/on_audio_query
# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  # on_audio_query
  on_audio_query_platform_interface:
    path: ../on_audio_query_platform_interface
  on_audio_query_windows:
    path: ../on_audio_query_windows

  # Flutter
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # Material Design
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.lucasjosino.on_audio_query
        pluginClass: OnAudioQueryPlugin
      ios:
        pluginClass: OnAudioQueryPlugin
      windows:
        default_package: on_audio_query_windows
      web:
        pluginClass: OnAudioQueryPlugin
        fileName: on_audio_query_web.dart
