# ========
# author: Lucas Josino
# github: https://github.com/LucJosin
# website: https://www.lucasjosino.com/
# ========
name: on_audio_query_platform_interface
description: A common platform interface for the [on_audio_query] plugin.
homepage: https://github.com/LucJosin/on_audio_query/tree/main/packages/on_audio_query_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.7.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  # on_audio_query
  plugin_platform_interface: ^2.1.2

  # Flutter
  flutter:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
